### PR TITLE
improve windows

### PR DESCRIPTION
**Pull request by DioEgizio**

### CODE REVIEW

**Comment by DioEgizio** [comment]
> I think the bit about legacy windows support should stay the same. The average probably user won't know what or why a dependency has anything to do with their launcher not opening and it probably should be made clear that they may not get support for any issues they may have. I do like the encouragement to upgrade at the end though.

i kinda agree, but:
- 8.1 has no reason to not work atm
- that way we're explaining more technically
- why would we not support people using win7/win8.1?

**Comment by Regular-Baf** [comment]
Yeah then I do agree about windows 8 then. But as for 7, I think it's worth being clear about not making promises, and the wording I originally used is probably best. For most users it's already EOL. I do think a technical explanation could be good, but it shouldn't be the focus.

**Comment by DioEgizio** [comment]
@Regular-Baf is it better now?

**Comment by Regular-Baf** [comment]
This look great to me

**Comment by ZekeSmith** [comment]
alright ill update this

**Pull request merged**
