### PR TITLE
Revert 'Pride'

### PR DESCRIPTION
**Pull request by glowiak**
It's shame and not 'pride'

### CODE REVIEW

**Comment by glowiak** [comment]
@Scrumplex inclusiveness does not mean supporting one side.

**Comment by glowiak** [comment]
Like I create a launcher that everyone is using and then put Donald Trump's face as the logo. How would you react?

**Comment by Scrumplex** [comment]
Do you want to explain to me why you think a rainbow flag discriminates you?

**Comment by Scrumplex** [comment]
> It's supporting the V collumn

Don't know what that means

> Not only me, but majority of world citizens

I am not LGBT myself and I don't feel discriminated, by a rainbow flag.

**Comment by Scrumplex** [comment]
> At least tell me, why you guys must push POlitics into launcher?

We have many users that identify themselves as LGBT. Often times gender and sexual orientation is part of their identity, which we are acknowledging by adding a rainbow flag to the logo.

**Comment by glowiak** [comment]
The V collumn, or targowica (officially called "opposition") is an evil organization that tries to make the State fall.

multimc is bad, but they at least don't push POlitics into their launcher

**Comment by Scrumplex** [comment]
Interesting conspiracy theory you got there.

> When they will promote self-kill, then you will change the logo to a gun?

Who is "they" and how is suicide related to a rainbow flag.

> Will be this horrible thing forever on the website?

It is pride month, so it will probably be on the website for June. Maybe longer if people like it.


I want to remind you that we are all human beings. Respect each other, even if you don't like someone's gender or sexual orientation. This is not about politics. This is about being inclusive to all people in society, not just the majority.

**Comment by glowiak** [comment]
"Who is "they" and how is suicide related to a rainbow flag."

"They" (Oni) is €uropean union (in Poland called "€urokołchoz").

They push ideology that is followed by 1-2% of the society, and discrimines The Majority.
They also push eKOlogy, veganism, which is also bad.

Let's say the entire humanity are vegans, next they are going to say that "bread feels" etc.

SO I AM GOING TO REVERT ALL MY COMMITS INCLUDING PORTS HERE.

**Comment by ZekeSmith** [comment]
Damn

**Comment by AntogamerYT** [comment]
It's an idiot, not a person (glowiak)

**Comment by Titaniumtown** [comment]
> "Who is "they" and how is suicide related to a rainbow flag."
> 
> "They" (Oni) is €uropean union (in Poland called "€urokołchoz").
> 
> They push ideology that is followed by 1-2% of the society, and discrimines The Majority. They also push eKOlogy, veganism, which is also bad.
> 
> Let's say the entire humanity are vegans, next they are going to say that "bread feels" etc.
> 
> SO I AM GOING TO REVERT ALL MY COMMITS INCLUDING PORTS HERE.

dude has severe mental issues. what the fuck.

**Pull request closed without merging**
