### PR TITLE
Run markdownlint on markdown files

### PR DESCRIPTION
**Pull request by txtsd**
One rule per commit

I've added the config to run it in the last commit. Let me know if it's unnecessary and I'll remove it.

There are still some suggestions that show when running `markdownlint .` These are edge cases and would ideally be ignored. I'd like help with ignoring them specifically without adding comments to the markdown files themselves.

### CODE REVIEW

**Comment by Scrumplex** [comment]
Conflicting again xD

**Review by Scrumplex — APPROVED** [review]

**Comment by DioEgizio** [comment]
Sorry! D:, probably will conflict again with #184

**Comment by txtsd** [comment]
Dang should I wait for that to be merged first?

**Comment by DioEgizio** [comment]
That's already merged, lol

**Comment by txtsd** [comment]
Okay rebasing in a bit.

**Comment by ZekeSmith** [comment]
Very interesting to read through the changes. Really shows how many things can be overlooked in something as simple as markdown. Im thinking it might be a good idea to put a linter into the development build so it checks files before publish.

Let me know once you have fixed conflicts and ill merge this.

**Comment by txtsd** [comment]
@ZekeSmith Conflicts are fixed! Please re-review though. I checked, but I might've bork'd something while rebasing.

**Comment by flowln** [comment]
> Im thinking it might be a good idea to put a linter into the development build so it checks files before publish

I guess we could do something like https://github.com/igorshubovych/markdownlint-cli#use-with-pre-commit :^)

**Review by flowln — APPROVED** [review]
idk how this works, but this won't trigger the rss feed, right? monkas

looks good to me!

**Comment by txtsd** [comment]
I think it will mark the posts as updated. At least it won't create new posts like that one time haha.

**Comment by txtsd** [comment]
> > Im thinking it might be a good idea to put a linter into the development build so it checks files before publish
> 
> I guess we could do something like [igorshubovych/markdownlint-cli#use-with-pre-commit](https://github.com/igorshubovych/markdownlint-cli#use-with-pre-commit) :^)

There are some warnings that I don't think need fixing. We should be able to filter those out if we use a pre-commit hook.

```
λ markdownlint .                                                                                                                                                                             
src/wiki/development/build-instructions.md:134:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
src/wiki/development/build-instructions.md:250 MD024/no-duplicate-heading/no-duplicate-header Multiple headings with the same content [Context: "### Build dependencies"]
src/wiki/development/build-instructions.md:263 MD024/no-duplicate-heading/no-duplicate-header Multiple headings with the same content [Context: "### Building a portable binary"]
src/wiki/development/build-instructions.md:276 MD024/no-duplicate-heading/no-duplicate-header Multiple headings with the same content [Context: "### Building & installing to t..."]
src/wiki/getting-started/command-line-interface.md:10 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
src/wiki/getting-started/installing-java.md:100 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
```

**Comment by ZekeSmith** [comment]
Theres a couple more conflicts but I can probably resolve them when im back on my desktop.

**Comment by txtsd** [comment]
Fixed conflicts again.

**Comment by Scrumplex** [comment]
:eyes:

**Comment by txtsd** [comment]
Dammit I'll do it again!
_runs into nvim like a barbarian_

**Comment by txtsd** [comment]
Okay, fixed conflicts again!

**Comment by DioEgizio** [comment]
Ig it can be merged now then

**Comment by Scrumplex** [comment]
@ZekeSmith should also review this first

**Comment by DioEgizio** [comment]
https://github.com/PolyMC/polymc.github.io/pull/183#issuecomment-1191079064

**Pull request merged**
