### PR TITLE
Purge glowiak's presence in the wiki

### PR DESCRIPTION
**Pull request by mikoxyz**
@glowiak is notoriously just extremely childish and a massive asshole on his reddit (see below,) in such a manner that some of it is in clear violation of PolyMC's code of conduct.

See:
[transphobia, homophobia] https://old.reddit.com/r/conlangs/comments/stskf1/gender_neutral_pronouns/hx64nym/
[racist drivel in polish] https://old.reddit.com/r/BSDmemes/comments/p0x1sf/why_i_was_banned_from_rfreebsd/h8ibbuj/

### CODE REVIEW

**Comment by LennyMcLennington** [comment]
We're not removing or rejecting contributions based on anything about person that made them, that's not what the CoC is about. If the contributions themselves break the CoC, then you should report them privately through the process described in the CoC.

**Comment by mikoxyz** [comment]
I would argue that glowiak indirectly represents the PolyMC community, or at the very least is endorsed by the PolyMC maintainers, since his stuff his linked in the official wiki (albeit branded as "community maintained,") so it's arguably within the scope of the CoC.

Anyhow, cool to see where PolyMC stands on issues like this.

**Comment by Scrumplex** [comment]
> I would argue that glowiak indirectly represents the PolyMC community.

No. That is a completely false assumption. In fact we have a few other community maintained packages in our wiki. The only people that represent PolyMC are the members of this GitHub organization.


> Anyhow, cool to see where PolyMC stands on issues like this.

We are not here to background-check and screen all our contributors. The CoC's scope is limited mostly to our own platforms. glowiak didn't do anything wrong in our channels. If you were personally attacked by glowiak because of this, feel free to open a case at the email provided in the CoC.

**Comment by Scrumplex** [comment]
This happened either way ¯\\_(ツ)_/¯

**Pull request closed without merging**
