### PR TITLE
Switch to new logo

### PR DESCRIPTION
**Pull request by Scrumplex**
Also switch fonts to Inter and Josefin Sans

Screenshot

### CODE REVIEW

**Comment by dschemp** [comment]
imo Josefin Sans should not be used for the buttons but rather for headers instead. It doesn't look right like it is here.

**Comment by dschemp** [comment]
I have to admit: I love the contrast in fonts in the nav bar between the logo and the navigation items.

**Comment by txtsd** [comment]
Yea the buttons font looks odd now.

Also, I stared at the `PolyMC` in the hero image for a good 30 seconds until I realized it wasn't changed lol. I didn't even see the font change at the top left until later. Maybe change all instances of the word `PolyMC` to use the new font?

**Comment by ZekeSmith** [comment]
I don't like the approach of hard coding the logo text into the icon I don't think it works well for screen readers and is generally not good practice if memory serves me right. I am also not sure about changing away from system fonts.

**Comment by dschemp** [comment]
_Not_ changing away from system fonts / system-ui would be a bad idea. system-ui as it seems is _very_ dependent on the system and language and can mess up the look, the website should have (https://infinnie.github.io/blog/2017/systemui.html). In this case, we should have control of this.
The alternative would be to use `sans-serif` and so on as fonts but this does not fit in here because it changes the way how the website is displayed. It wouldn't be a problem for e.g. a docs page but here it is.

About the logo: I honestly don't think screen reader will be an issue as it is just the logo. You don't really have to read that out. Correct me if I am wrong but for accessibility we have [aria attributes](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA).
Other than that: I don't see a problem on using an svg (or alike) as a logo. Logos are a product of design. You cannot recreate everything with the methods browsers provide (and possibly shouldn't). YouTube for example uses an svg icon embedded onto the website.

**Comment by Scrumplex** [comment]
We could also just use Inter exclusively on the site. Josefin Sans isn't ideal as an UI font. IMO there is no reason to use it outside of the logo.

**Comment by Scrumplex** [comment]
image

**Comment by ZekeSmith** [comment]
Alright this seems all good.

**Pull request merged**
