### PR TITLE
Use 11ty image instead of CSS background-image for hero

### PR DESCRIPTION
**Pull request by oynqr**
Some settings still need tuning to get to the same file size as the original forest.webp, but otherwise this works pretty good.

### CODE REVIEW

**Comment by oynqr** [comment]
This makes webp lossless by default, which works very well for the screenshots.
AVIF is also added for the hero background, although decode times might be an issue.

**Comment by ZekeSmith** [comment]
I cant actually replicate this pull on my device it doesnt seem to load the background image at all and I am generally worried about compatibility using an <picture> with absolute positioning. I do like some of the changes to the image compression and code cleaning however I dont think having a formats option for the shortcode makes sense. I also think its not worth having Avif instead we should just use webp, jpeg, png for all images as adding avif on top of those 4 adds more rendering time.

**Comment by oynqr** [comment]
I'll test on a bunch of browsers, post some results later.
Neither JPEG nor AVIF are suitable for the screenshots, as JPEG doesn't support transparency and AVIF sucks at compressing screenshots (at least in its lossless mode).
Having the format option on the shortcode is worthwhile since most of the images are GUI screenshots with transparency, where lossless WebP and PNG shine. Specifying additional formats for the odd image that doesn't compress well losslessly seems like a decent tradeoff to me.

**Comment by oynqr** [comment]
Alright, here's my _site bundle and some screenshots from a bunch of browsers. Might also try Edge and IE in the future for fun. The only one where it doesn't look the same is on NetSurf, since that doesn't support CSS filter, but there's a lot more issues on NetSurf than that.
[_site.tar.gz](https://github.com/PolyMC/polymc.github.io/files/8212637/_site.tar.gz)
[screenshots.tar.gz](https://github.com/PolyMC/polymc.github.io/files/8212646/screenshots.tar.gz)

**Comment by oynqr** [comment]
Force pushed to keep commit history clean.

**Comment by oynqr** [comment]
Here's some more screenshots, taken from the official Microsoft Browser evaluation VMs. IE11 actually works better, although it uses the huge png. Edge Legacy works fine in both cases.

[ie11_css](https://user-images.githubusercontent.com/71629732/157418630-34cdfc97-39e8-407c-b0b9-34162e2e39bf.png)
[ie11_picture](https://user-images.githubusercontent.com/71629732/157419029-13d58460-53fe-44d6-bcca-55101f8d25d1.png)
[edge_css](https://user-images.githubusercontent.com/71629732/157419056-cef25961-ca6c-4abf-b354-096cb9f72535.png)
[edge_picture](https://user-images.githubusercontent.com/71629732/157419081-e7755abc-a56e-427b-84a1-983b7e26b561.png)

**Comment by ZekeSmith** [comment]
Yep it all looks good now

**Pull request merged**
