### PR TITLE
Update download.md

### PR DESCRIPTION
**Pull request by DioEgizio**

### CODE REVIEW

**Comment by Scrumplex** [comment]
Maybe just say "Download source (.tar.gz)"

**Comment by DioEgizio** [comment]
> Maybe just say "Download source (.tar.gz)"
But it's note, it's the tar.gz binary tarball for binary packages (for polymc-bin mostly)

**Comment by DioEgizio** [comment]
> Oh. Didn't check. Hmm but you technically can use that as a portable binary, it just won't store data in the same directory

But it's not actually portable.
Also https://github.com/PolyMC/PolyMC/issues/258

**Comment by Scrumplex** [comment]
isn't it all statically linked now?

**Comment by Scrumplex** [comment]
yes it is, should be fine

**Comment by DioEgizio** [comment]
Oh yeah. 
Still it's not actually portable and it's meant for packaged so idk

**Comment by Scrumplex** [comment]
Dunno. In that case I would just remove the download button.

**Comment by ZekeSmith** [comment]
Whats the point in this?

**Pull request closed without merging**
